### ISSUE TITLE
How to Contribute?

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#1]
Would you like us to fork and send a PR?  Or to work on our own branch, and send a PR from there?  Or some other workflow?

**Comment by kduncklee** [comment]
Either way is fine. We've been making branches and doing a PR from the branches.

**Comment by andyl** [comment]
OK I'll do it the branch way.  Most of my contributions will be docco.  I'll push my WIP to the `deva` branch.
