### ISSUE TITLE
Member Cert functionality needs work

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#106]
- [ ] backend need storage for documentation

- [ ] cert "add", link input is limited to HAM and comment to others, does that make sense?  Where are documentation links displayed
 
- [ ] cert "edit" needs upload after backend work is complete

**Comment by ctaylor451** [comment]
How do we upload certs?

**Comment by kduncklee** [comment]
From the user cert edit page, select 'add.' On the cert add page, there is a "cert file" upload field.
