### ISSUE TITLE
Event OP API needs to accept empty string and delete data as appropriate

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#112]
Currently there is no way to reset dates.  Ex. "edit" leave date on OP

**Comment by kduncklee** [comment]
Pass null instead of the empty string. See the member cert page for an example.

**Comment by ctaylor451** [comment]
I checked in changes to deal with deleting entries.  Our changes are
starting to conflict.  The FE need empty strings for editing that are
converted to nulls during the Ajax call.  The table rows should never have
nulls
