### ISSUE TITLE
Use 24 hour clock for Events

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#131]
Instead of AM/PM

**Comment by jboning** [comment]
This is browser-dependent. Chrome shows 24h times while Firefox shows AM/PM. On mobile you get the native date picker, which uses whatever you've set your device to.

We could try to use some library on web; I don't think we're going to find a nicer experience on mobile than the native UI.

**Comment by ctaylor451** [comment]
Josiah, agreed, you and I went around on this.  My vote is mobile first.  
@andyl , I'm closing this now but feel free to reopen if you disagree
