### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#132]
Integrate BAMRU.net V2 with our public calendar on BAMRU.org

**Comment by kduncklee** [comment]
I added the published filter. Please let me know if there is anything else you need for this.

**Comment by jboning** [comment]
Code is here: https://github.com/BAMRU-Tech/bamru-gcal

It seems to work well enough, though session timeout is probably an issue. When I get a chance (tomorrow or Thursday evening??) I'll look into adding OAuth support on the server-side, then we can switch the gcal tool to use that.

Unassigning myself for the operational side of things.

**Comment by ctaylor451** [comment]
With the new system is there any reason not to integrate with event
creation directly?

**Comment by ctaylor451** [comment]
@jboning what's the status of this code?  Would you propose an integration plan?

**Comment by ctaylor451** [comment]
Texted @jboning waiting for reply on integration

**Comment by jboning** [comment]
As a minimal solution, I can set this up as a cron job running on a machine I have access to. I can do that tomorrow.

A better approach is to set this up as a cron job running on some bamru-managed machine. I can take a look at how to do that with our vagrant tooling on Sunday.

The ideal would be to update gcal events in realtime when events are created/edited/deleted on bamru.net. Even if we do this, though, we'll still want a cron job to periodically resync the calendar, in case some update request fails. So we might as well start with one of the first versions.

(Side note: The code I wrote only syncs to google calendar, not bamru.org. It looks like there's another (manual?) set of steps needed to update bamru.org. I'll look into that more on Sunday as well.)

Taking a step back: is any of this needed for MVP? Given that the public calendar is fairly stable, I don't think automatically updating the google calendar is critical within the next month or two.

**Comment by jboning** [comment]
Maybe I misunderstand the MVP--I thought the goal was to get an operationally stable system that we could use to send pages as soon as possible. (Maybe I'm out of date because I've been missing the Tuesday calls.)

I'll look at this now.

**Comment by ctaylor451** [comment]
Thanks.

Current plan is to move completely, think Google beta. Operations have been
difficult without a working system so we want to get all the components
running.  Kevin has the wiki upgraded with oauth.  We're working to get all
the functional pieces are in place, ideally by next week.

Cheers, Craig

**Comment by ctaylor451** [comment]
Thanks.  You obviously don't live or die by your Google calendar ;-)

**Comment by ctaylor451** [comment]
Did you intend to reference #208 instead of #203?

What's left to do for incremental update, just add credentials?

**Comment by jboning** [comment]
Er, yep, I did.

Just credentials. Working on that now.

**Comment by ctaylor451** [comment]
We also have a bamru test calendar account. Do you needed it?

**Comment by jboning** [comment]
The credentials on the wiki for that are up to date (thanks Andy!) so I've been using it to test already.

**Comment by ctaylor451** [comment]
What's the next step?  I'd like to setup my dev env and test it out

**Comment by jboning** [comment]
I just landed the PR, so if you pull and run the vagrant setup on your dev env, you should be able to see event changes reflected in the bamru.caltest gcal.

**Comment by ninjadeathtoast** [comment]
Agree that this isn't a critical issue for posting to bamru.org, but since we do have recruiting season starting with guests probably trying to look up dates, can it be "slightly more important than other less-important things"?

Or we don't publish and test their resourcefulness ;)

**Comment by ctaylor451** [comment]
It's pretty much done. Josiah implemented the code so it just needs a
little more work to deploy.  Currently it generates a 500 error that we
haven't had time to look at

**Comment by jboning** [comment]
Reference discussion on #231 - google calendar sync is now fully deployed!

I'll leave this issue open for getting updated info onto bamru.org as well. That looks like it shouldn't be hard--hopefully I'll have time to look at that soon.

**Comment by kduncklee** [comment]
Calendar is now automatically updating.
