### ISSUE TITLE
receipt confirmation requires y/n should allow OK

### ISSUE THREAD

**Issue by ninjadeathtoast** [BAMRU-Tech/bamru_net#154]
![screenshot_20181106-084912](https://user-images.githubusercontent.com/44073571/48079813-04b8bc00-e1a1-11e8-8207-fbc30afb3463.png)
Today's SMS page came through, so I replied "OK" like I have always done to mark the message as read. It's not a huge thing, so I'd be happy to label this as low priority/non-important, but we used to be able to reply with anything to the DO page to notify the system we had read the message. Like I said, not a major thing so happy for the dev team to close this if that makes sense.

  -Adam

**Comment by kduncklee** [comment]
Thanks for the report. I can see the use for this and also use for displaying the actual text responses.

**Comment by kduncklee** [comment]
This is partially handled by #415. The intent is to show the incoming responses on the event page (like #398).
