### ISSUE TITLE
Text pages missing action links

### ISSUE THREAD

**Issue by dschott68** [BAMRU-Tech/bamru_net#162]
![img_0629](https://user-images.githubusercontent.com/214201/48292333-c20c1380-e42e-11e8-9ff4-6a822e909ec0.PNG)

Missing link or call to action for the messages.  Additionally, not clear how I'd reply to the first message independent of the 2nd message.  If I replied Y or Yes, then is that for the 1st or 2nd message or both messages?

**Comment by ctaylor451** [comment]
Seems like an artifact of #164

**Comment by kduncklee** [comment]
Fixed along with #164 in PR#193
