### ISSUE TITLE
Manually adding members to event doesn't work

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#169]
When adding a member to an event, from the event page clicked on the "Add" button which takes you to the roster. I searched for the person and then clicked in the left most box (for the checkmark). Then, searched for another member, did the same thing, etc. At the end, clicked "Add" expecting to add everyone that had a checkmark. However, that was not the case and only the last person was added.

**Comment by kduncklee** [comment]
I saw this too. It looks like members are deselected when the filter excludes them. It should remember the selection even when they are hidden.

**Comment by ctaylor451** [comment]
Seems like a design question buried in this issue.  You can use search to limit the view and select members.  For the filters to we want a bunch of hidden check marks?  Feels like bad UI

**Comment by melinanina** [comment]
I went to test it again to try to understand @ctaylor451 's comments, but the issue seems fixed? Did something change?

**Comment by ctaylor451** [comment]
Filtering still deselects, are you thinking of being able to add a 'R' member?  I did fix that

**Comment by melinanina** [comment]
I just tested again, and the original issue is indeed fixed (if selecting users, it adds all the users).

However, when you add the filter, then it deselects all previous selections, which is not what I expected. I would expect it to deselect the users that no longer meet the filter criteria.

**Comment by ctaylor451** [comment]
Maybe we should talk directly.  I'm not understanding the use case

**Comment by ctaylor451** [comment]
Closing for now, happy to discuss at a later date
