### ISSUE TITLE
Email: Add link to associated event

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#172]
We did a scenario with many operational periods.  All pages appeared in my email inbox in a single thread.

![image](https://user-images.githubusercontent.com/90030/48305254-3b157480-e4dc-11e8-8735-07137e7cb0a0.png)

Feature request:

- [x] add a unique ID to the subject line so that each email is tied to a unique OP
- [ ] put a link into the outbound email that takes the viewer back to the OP and outbound page on BAMRU.net

**Comment by kduncklee** [comment]
Unique ID added in #161 / #167 

Link to event is a good idea. Thanks!
