### ISSUE TITLE
Single-Click "left now" for DO

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#173]
the DO can manually enter a member's "left-at" time.

Feature request: create a button to have a one-click -"left-at-now" to streamline the UI flow

**Comment by ctaylor451** [comment]
Not sure I understand this request.  What does the button do?  Just set the current time as the left time? How often does this happen, I would have thought that most left times are relatively unique

**Comment by kduncklee** [comment]
This is useful for checking in/out multiple people at once, sometimes when people forgot to respond. It sets the left/returned time to the current time. See the 'N' link on the current site for an example.
