### ISSUE TITLE
oauth support for API

### ISSUE THREAD

**Issue by jboning** [BAMRU-Tech/bamru_net#179]
The API is fairly comprehensive; it would be great to support external access via OAuth tokens (rather than by copying a session cookie from the browser).

**Comment by ctaylor451** [comment]
Seems like a great idea as long as we can contain the complexity.  A key goal of this rewrite was to make it approachable and easy to maintain by occasional tech contributors.  I'm hoping we can eventual write an app but that may violate the simple and approachable principle.

**Comment by ctaylor451** [comment]
Closing for now, move topic to FUTURE_WORK
