### ISSUE TITLE
Transition BAMRU.net Domain

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#188]
Here's the proposed transition sequence:
1) BAMRU.org - transfer from Tucows to Namecheap ASAP
2) BAMRU.info - transfer from Godaddy to Namecheap ASAP
3) BAMRU.net - transfer from Godaddy to Namecheap AFTER BAMRU.net V2 is proven stable

**Comment by andyl** [comment]
Craig says:

    I don't think we can retire the old system for a while.  
    It still has cert documentation for sure and I think it is 
    the file repository for the wiki.

    Can we move the old system to old.bamru.net under 
    namecheap and redirect it to the existing server?

**Comment by andyl** [comment]
Andy replies:  I added a CNAME record for 'old.bamru.net' to the Godaddy config.  I added 'old.bamru.net' as an NGINX alias on the BAMRU.net server.

HTML access is working for 'old.bamru.net'.  If we point the 'bamru.net' domain to the new system, email paging will break on the old system.

**Comment by ctaylor451** [comment]
Once the new system is stable, having the email paging turned off on the old system should be OK

**Comment by ctaylor451** [comment]
Does the old system hold uploaded files for the wiki?  I vaguely remember that the file upload had some 'special' behavior

**Comment by andyl** [comment]
Uploaded files is part of the old system, not the wiki.  WIKI urls that link to a url like `http://bamru.net/files/XXX` would break if we point `bamru.net` to a new server.  A possible workaround would be to create a route on the new system that redirects requests from `bamru.net/files/...` to `old.bamru.net/files/...`.  (note there is no SSO & potential confusion as usernames / passwords diverge on the old and new systems...)

**Comment by ctaylor451** [comment]
Alternatively, can we copy the /files directory to the new server?  How
does the upload code get files to the server?

**Comment by andyl** [comment]
There's nothing complicated about storage on the old system - just files sitting on the file system.  It would be easy enough to put them in a tar file and copy them over.  There is file meta-data in the database (name of the file uploader, download counts).  IMO it would OK to wipe out the meta-data and start from scratch on the new system.

**Comment by ctaylor451** [comment]
Can I assign this issue to you

**Comment by ctaylor451** [comment]
@kduncklee are you still willing to implement the file upload page with Django?

**Comment by kduncklee** [comment]
Yes, it's next on my list.

**Comment by ctaylor451** [comment]
Another thought, what if we stay on bamru.info permanently.  It forces a change of behavior and doesn't roll off the tongue but seems like an option.  Move the wiki and new  system onto .info and skip the .net migration.  Still worth moving to namecheap so everything is in one place but the urgency is low

Thoughts?

**Comment by ctaylor451** [comment]
Can we move to the new wiki ASAP, (as soon as we have file upload)?  Point the old bamru.net to the new wiki once we are on namecheap

**Comment by andyl** [comment]
Note: as of 27 Nov Shane is working on transferring BAMRU.org to NameCheap

**Comment by kduncklee** [comment]
This is now all done. The domains and DNS are all now on namecheap.
