### ISSUE TITLE
Events list page sorting

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#197]
- [x] The default sort order on the event list page should be by date.

- [x] Also, I think currently active events should show up in the top (upcoming) section.

**Comment by ctaylor451** [comment]
Regression on the sorting, fixed

Do you have an example of active event.  Top table is current date + 1 month based on start_date maybe I should make it end date

**Comment by ctaylor451** [comment]
Fixed in PR #198

**Comment by ctaylor451** [comment]
Fixed pr #304
