### ISSUE TITLE
Ansible provision fails if migration asks questions

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#199]
I upgraded staging 
apt-get upgrade

vagrant provision
now hangs at: TASK [django setup script] 

Also see this error, I don't remember this before:
Using /etc/ansible/ansible.cfg as config file
/home/bamru/bamru_net/deploy/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/home/bamru/bamru_net/deploy/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory did not meet script requirements, check plugin documentation if this is unexpected

**Comment by kduncklee** [comment]
The underlying problem was that the migration asked questions. It then hung waiting for input. We should decide how to handle this. For now, you need to ssh in and manually run makemigration.

**Comment by ctaylor451** [comment]
Should we include --no-input or --noinput (not sure which, seems like both will work) on makemigrations and migrate?  Haven't had time to test

**Comment by kduncklee** [comment]
Issue is obsolete, as we will now commit migrations to the repo.
