### ISSUE TITLE
database backup on a regular schedule

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#203]
Before we go live we need a database backup strategy.  @andyl what are you doing for the current system?  I seem to remember some kind of cron job solution.  Not looking for implementation more ideas on how to solve the problem

**Comment by jboning** [comment]
In a past life I set up https://github.com/wal-e/wal-e on a quite large database. It wasn't super intuitive to configure but after getting it set up, I don't remember encountering any problems.

IMO we'd be better off paying for a hosted solution (amazon RDS or similar), though we'd want to move hosting into the same universe (ec2 or whatever) for latency reasons.

**Comment by ctaylor451** [comment]
Completely agree but not MVP.  I'll add an issue to cover this

**Comment by kduncklee** [comment]
This is now complete. Hourly backups to local disk, backed up to google drive.
