### ISSUE TITLE
Event Feature Issues

### ISSUE THREAD

**Issue by code-jockey** [BAMRU-Tech/bamru_net#211]
- [x] It is not clear what the "All Day" flag means.
- [x] It is not clear what the "Publish" flag means.
- [x] Clear for dates and times when editing a user's info for an Event OP period doesn't work on mobile (iOS)[CST: Is this still a problem? If so, let's open a separate issue]
- [x] When not populated yet, the time and date fields for editing a user's info for an Event OP period are too small to select on a mobile device (iOS phone)[CST: Is this still a problem? If so, let's open a separate issue]
- [x] Current state of Events page (selections and filters) is not maintained when going to the details page for an event and then clicking on the Events link to return to the event list page. (moved to #94)
- [x] There is no way to cancel adding users for an OP period when you are on the user selection page except using the browser's back button or worse yet clicking on the Events button in the main tool bar [CST: click on the op link or use the back button]
- [x] Deleting an event (published or not) doesn't remove it from the events list.

**Comment by ctaylor451** [comment]
#1 and #2 there are doc strings on the event create page

**Comment by ctaylor451** [comment]
There is no way to cancel adding users for an OP period when you are on the user selection page except "using the browser's back button or worse yet clicking on the Events button in the main tool bar"

What is wrong with the back button, that is pretty common on mobile.  We could have add not require a selection and just return.

**Comment by ctaylor451** [comment]
- [ ]  Clear for dates and times when editing a user's info for an Event OP period doesn't work on mobile (iOS)
- [ ]   When not populated yet, the time and date fields for editing a user's info for an Event OP period are too small to select on a mobile device (iOS phone)

Need more detail on what actions are you doing.  Works on chrome with datetime picker

**Comment by ctaylor451** [comment]
- [ ]  Deleting an event (published or not) doesn't remove it from the events list.

Need more detail, works on chrome

**Comment by code-jockey** [comment]
I just checked the latest code on 4 different browsers on an iOS phone and have the following updates:

The date and time fields are now large enough to be selected when they are not populated in all 4 browsers on my iOS phone.

The Clear button works for the date and time fields on my iOS phone, except for Chrome, where there is no Clear button at all.

The Cancel issue when adding users for an op period could be solved by the addition of a Cancel button, or we could leave it as is and the user could just click on the browser's back button or click on the op period navigation link to return. We are not at all consistent in what buttons appear on our various pages and dialogs, but we could leave it for now.

Deleting an event still does not remove it from the events list. This we should fix.

**Comment by ctaylor451** [comment]
Deleting events works for me.  Do you have an example

**Comment by ctaylor451** [comment]
Closed with comments.  If there are still problems let's open separate issues
