### ISSUE TITLE
Consider hosting solution for DB 

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#214]
@jboning says, In a past life I set up https://github.com/wal-e/wal-e on a quite large database. It wasn't super intuitive to configure but after getting it set up, I don't remember encountering any problems.

IMO we'd be better off paying for a hosted solution (amazon RDS or similar), though we'd want to move hosting into the same universe (ec2 or whatever) for latency reasons.

**Comment by kduncklee** [comment]
Closing for now. Our current setup is stable.

We can revisit as part of possible future discussion on hosting providers.

**Comment by ctaylor451** [comment]
Where are we going to document future ideas? I'm OK with something other
than the issues list

**Comment by ctaylor451** [comment]
Moved to FUTURE_WORK
