### ISSUE TITLE
Calendar code is causing a Server Error (500)

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#231]
On barmu.info when one checks the publish checkbox the server returns 500.  Probably a setup issue, can guys look at this @jboning or @kduncklee

**Comment by jboning** [comment]
I can take a look tonight if someone can point me in the right direction--I
don't know whether I have access to Sentry or the running system.

**Comment by ctaylor451** [comment]
I sent private message with info

**Comment by jboning** [comment]
OK, I got things configured in the user_vault.yml files, and everything should be up and running:
 - staging.bamru.info syncs to the testing calendar
 - bamru.info syncs to https://calendar.google.com/calendar/embed?src=bamru.calendar%40gmail.com&ctz=America%2FLos_Angeles

I'll leave this issue open to improve the error handling so we don't 500 if a request fails.

**Comment by jboning** [comment]
I also just added some notes about calendar in our docs

**Comment by ctaylor451** [comment]
Thanks! I'll check it out tomorrow

**Comment by ctaylor451** [comment]
Fixes in PR #232, #233, #234.  Thanks, Josiah
