### ISSUE TITLE
txt pages from bamru.info come on different phone numbers from before

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#244]
When I create an event and page myself from bamru.info, the text page comes on XXX-XXX-XXXX.

I do not have this number programmed into my Fire Alert, so my phone was silent as it usually is - was the unit informed of the new numbers? or will the old numbers be used? Very important for paging.

**Comment by kduncklee** [comment]
We're using a new service, so will have new numbers. We will mail the updated list out to the unit along with some instructions about the site.

**Comment by ctaylor451** [comment]
Message being sent to the team
