### ISSUE TITLE
unable to delete event

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#245]
I created a test event on bamru.info, called "Test Event."  I added myself, then removed myself successfully. There is an empty OP1, when I try to "Delete OP", OP1 remains - not sure if this is the desired behavior.

When I try to delete the event, "Delete" in top right, it asks me to confirm, "Delete event? test event", I click on okay, but it goes back to the event page, with the test event still there.

Repeated same problem on staging.bamru.info

**Comment by kduncklee** [comment]
This looks to be linked to this sentry issue:
https://sentry.io/bay-area-mountain-rescue-unit/django-prod/issues/802692205/

TypeError: Missing required parameter "eventId"
(7 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 93, in destroy
    self.perform_destroy(instance)
  File "main/views/api_views.py", line 110, in perform_destroy
    get_gcal_manager().delete_for_event(event)
  File "main/lib/gcal.py", line 82, in delete_for_event
    eventId=bamru_event.gcal_id,

**Comment by kduncklee** [comment]
I realized I missed one of your points. If you delete all the periods, a new OP1 is created. An event page should not exist without a period.

The rest should be fixed on staging.

**Comment by ekhco** [comment]
Yeah, that makes sense! Tested this AM and it works great - thanks!
