### ISSUE TITLE
How to send pages?

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#25]
I'm logged into the system but cant see any features that allow me to view or send pages.

Is this because I'm in reserve?

**Comment by jboning** [comment]
View pages via Library > Message Log or (User) > Inbox

Send pages from an event OP

It's definitely a different approach. Not sure whether it just takes some getting used to, or if we need to think about surfacing this differently.

**Comment by kduncklee** [comment]
We wanted to make it more difficult to send pages that were not attached to an event. This is a common DO mistake. We might add back in a "test page" option, but make it clear that it is only for testing.

**Comment by andyl** [comment]
Thanks for the explanation - I see the forms now.
