### ISSUE TITLE
Server error 500 

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#250]
I was testing staging.bamru.info on android - and navigated away and came back and refreshed (was on an event page intending to send a second "have you left page" after I text responded "Ni"

It went to a blank server error 500 page.i am unable to log back into staging.bamru.info w saved credentials. Says my credentials are wrong.

**Comment by ekhco** [comment]
Irreproducible ...

**Comment by kduncklee** [comment]
Sorry, I re-provisioned the server out from under you.
