### ISSUE TITLE
Refresh pointer to missing page

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#251]
After I try to page "have you left?" to an emtpy OP, and after I click okay to error popup, the page refreshed but goes to this page:

Not Found
The requested URL /event/2734/undefined was not found on this server.

**Comment by ekhco** [comment]
This also happens when trying to page an empty OP for: "Are you home", "Info (team)", "Broadcast (unit)", and "Test"

**Comment by ctaylor451** [comment]
Fixed PR #263
