### ISSUE TITLE
Unable to interact w last element of list

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#252]
In Android, when I click on page... Are you available? ... And the list of members appears, I am unable to interact w the last member on the list (coincidentally Eric Chow) ... I cannot select it to page, and cannot expand the green plus for details. I am able to interact w others listed above.

Might be a problem w the list ending right against the bottom of the screen? Maybe I have fat fingers. Reproduced 4/5 attempts so unsure of cause.

**Comment by ctaylor451** [comment]
I can't reproduce this

**Comment by ekhco** [comment]
this could be a bug with my phone and not specifically staging.bamru.info ... I can't consistently reproduce it either. Can table it for later.
