### ISSUE TITLE
"Clear All" very close to "Send Page"

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#254]
In paging "Heads Up" (or any paging function) on android, the "Clear All" button is VERY close to the "Send Page" and I have to click very carefully with my finger to clear all instead of sending the page.

Perhaps the buttons can be flowed with more vertical padding to avoid a miss-click?

![screenshot_2018-12-11-19-12-26](https://user-images.githubusercontent.com/1657391/49846157-b9389580-fd7e-11e8-860a-6a6dbc40fc31.png)

**Comment by ctaylor451** [comment]
Closing for now since I haven't had any additional feedback
