### ISSUE TITLE
Awkward text edit size for "Event info" in mobile

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#255]
When creating an event on mobile, when I finish entering the title and go the description box, it automatically scrolls down and then I can't see what I'm typing anymore for the description.

Perhaps the entry box can be made to be shorter, so that I can still see the first line of it, with the keyboard on the mobile screen.
<img width="359" alt="screen shot 2018-12-11 at 8 23 59 pm" src="https://user-images.githubusercontent.com/1657391/49847037-f56df500-fd82-11e8-96a4-113b98658af8.png">

**Comment by ctaylor451** [comment]
Reduced to 4 rows PR #264
