### ISSUE TITLE
Add quick "copy" button to member phone?

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#256]
In Android, I often have the use-case of looking someone up, and then wanting to text or call them... but then I have to awkwardly select their phone number, and adjust the little selecter bars to get only the phone number, so I can paste it into my caller. Often times, I just write down the phone number from my phone onto paper with a pen... and then re-enter it again later, because I'm in a moving car and it's hard to select the phone number.

It would be AMAZING if I could click on the phone number and it would be copied to my clipboard on the phone!

Also, I feel like too much of the name is cut off in the member list...
<img width="522" alt="screen shot 2018-12-11 at 8 40 16 pm" src="https://user-images.githubusercontent.com/1657391/49847650-0704cc00-fd86-11e8-850a-21f9499e1c62.png">

**Comment by kduncklee** [comment]
We should use the tel attribute: <a href="tel:555-555-5555">555-555-5555</a>

This will invoke the native phone apps on iphone and android.

**Comment by ctaylor451** [comment]
Fixed #266
