### ISSUE TITLE
Would be useful to see who has passed SO background (in case we need to field promote an OL)

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#260]

**Comment by ctaylor451** [comment]
From Cody:
What to you think about a column that says “SO”.  If background is passed, there is a badge.  If certified driver, there is a steering wheel.  If you mouse over the star or steering wheel, it will say “Background passed” or “Certified driver”.  If this is too tricky, background is more important than driver

**Comment by kduncklee** [comment]
I think a good short-term fix would be to set the responsive level of columns like ICS and rigging to be more hidden than SO background and driver.
