### ISSUE TITLE
Will member photos be added?

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#262]
Early on in traineeship, I found the "Photos" page very helpful, as I could recognize people's faces, but forget their names - so I would go to the Photos page and look for the face I recognized, and could remind myself of their name. Will this function/page be added later?

On the flip-side, perhaps there is also utility in having the photo next to the name (so if I know the name, but haven't met the person yet, I can then see who to look for).

**Comment by kduncklee** [comment]
Yes, this is in the plan. We'll migrate the images and data over initially and add the functionality to display them and upload new images.

**Comment by kduncklee** [comment]
Pushed to prod.
