### ISSUE TITLE
missing phone number of member prevents page to all members

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#267]
I tried to do a "heads up" SMS-only page to Stefan (who has NO phone number) and to Eric (who has a phone number), I got this error pop-up and the page was not sent to Eric (and probably wasn't sent to Stefan either).

![screen shot 2018-12-13 at 7 06 07 am](https://user-images.githubusercontent.com/1657391/49947235-981e9480-fea5-11e8-825e-27f9d44523b1.png)

*update* I tried to do an "email" AND "SMS" page to Stefan (who has NO phone number, but has an email) and to Eric (who has both email and phone number). No page was received by Eric (nor Stefan presumably) by email or text.

*update* I tried to do an "email" only page to Stefan (who has NO phone number, but has an email) and to Eric (who has both email and phone number). No email page was received by Eric (nor Stefan presumably) by email.

*update* I tried to do an "email" AND "SMS" page to Craig (who has phone number and email) and to Eric (with a WRONG phone number, and email). I received the email page, no txt page (as expected). Craig got the pages.

*update* I changed my phone number to not be pageable in my profile and repeated above - I received the email page, no txt page (as expected). Craig got the pages.

**Comment by kduncklee** [comment]
This looks to be a javascript issue. Any members added to the table by relaxing the filter do not have the data('id') attribute set. Thus the member number is not set on the POST to /api/messages/.

**Comment by ctaylor451** [comment]
Fixed PR #272
