### ISSUE TITLE
Paging / Member Select

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#27]
When I send a 'test page', the member list is empty.

When I send a 'heads up page', the member list is populated, but I can't send to individual members.

**Comment by ctaylor451** [comment]
Current by design.  For MVP paging is driven thru events.  Obviously this is a longer discussion

**Comment by ctaylor451** [comment]
This should be fixed in the current implementation.  Please let me know if this doesn't handle your concern
