### ISSUE TITLE
Consider adding BAMRU logo?

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#274]
It would be _really_ cool if we replaced the little graph icon (which kinda looks like a mountain?)
<img width="36" alt="screen shot 2018-12-16 at 11 37 46 pm" src="https://user-images.githubusercontent.com/1657391/50072873-9bf33500-018b-11e9-87df-0a44855929a2.png">

with the BAMRU logo! here's a tiny 128x128 35K PNG with transparency (resize to taste):

![logo_trans_35k](https://user-images.githubusercontent.com/1657391/50073042-263b9900-018c-11e9-99b0-f9263ee01f7f.png)

**Comment by ekhco** [comment]
This is so awesome. Love it

**Comment by ctaylor451** [comment]
You're welcome 😏
