### ISSUE TITLE
Always sub-sort names?

### ISSUE THREAD

**Issue by kantarjiev** [BAMRU-Tech/bamru_net#280]
When looking at the roster, names don't appear to be sorted when sorting by other columns. For example, when sorting by Status, it would be much more useful if the names in each grouping were sorted.

**Comment by ctaylor451** [comment]
The rows are sub sorted based on the last sorted field.  Initially sorted by roles so if you sort by status the subsort is roles

**Comment by kantarjiev** [comment]
Ok thanks, I get the current operation now.
