### ISSUE TITLE
Shutdown old machines

### ISSUE THREAD

**Issue by andyl** [BAMRU-Tech/bamru_net#283]
I'm going to shutdown the old BAMRU.net and wiki.BAMRU.net machines today.

I still get charged for a machine even if it is shut down, so I will destroy these machine images in a week's time.

If you want to transfer the machine images to another Linode account, send me the instructions on how to initiate the transfer.

**Comment by kduncklee** [comment]
Please wait. We want these up as a reference and in case something goes wrong.

Let's plan to leave them up for one month.

**Comment by andyl** [comment]
Old machines are offline.  If you want to transfer them to another Linode account let me know - I can initiate the transfer, or give you my username/password and let you manage both the send/receive side.

**Comment by andyl** [comment]
Kevin and I agreed to this plan:
- restart the old bamru.net and leave it running for a month
- andy to continue paying the hosting costs
- leave wiki.bamru.net down, and destroy it in a week's time
- destroy the old bamru.net in a month

FYI the old machine is now reachable at http://old.bamru.net

**Comment by ctaylor451** [comment]
Let's make sure that we investigated and verify that the new system implements all the needed reports

**Comment by ctaylor451** [comment]
Can we close this machines down?

**Comment by kduncklee** [comment]
This is done.
