### ISSUE TITLE
deleting events delete message logs also

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#288]
If an event is deleted, all the associated messages and responses to that event are also deleted and no longer show up in the message log.

I wonder if this is ideal? Should the message log be persistent? ie: if a message was sent, and someone read and saw it (and it altered their understanding of the state of an operation), it should forever be in the log as documentation, even if the event it was for gets deleted at a later time (perhaps as a temporary fix, or as a work-around).

**Comment by kduncklee** [comment]
Agreed that it should not delete the messages.
