### ISSUE TITLE
slightly incorrect times in message log

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#290]
The message log shows a slightly incorrect time (12 minutes later), not sure if server needs its clock adjusted.

![screen shot 2018-12-20 at 6 07 20 pm](https://user-images.githubusercontent.com/1657391/50320674-4c11b800-0482-11e9-9534-8858e36871f9.png)

**Comment by kduncklee** [comment]
The server time is correct. The time in the log files is also correct. I'll try to figure out what's going on.

**Comment by ctaylor451** [comment]
@kduncklee , any progress on this?  Seems weird

**Comment by kduncklee** [comment]
I looked at it a couple times now. The server time seemed right and I can't figure out where the bad time came from.

We might want to move away from auto_now_add fields and implement it ourselves for more control. Maybe also add more detailed logging on this.

**Comment by kduncklee** [comment]
This was also fixed by #401
