### ISSUE TITLE
consider displaying "availability" status in message log /  paging

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#292]
in the old bamru.net, one could see the availability status for members (ie: if they were out of town etc) while paging. Which might have been useful when chasing down people who haven't responded to pages ("oh, she's still PENDING because she's in another country")

It would be helpful if the message log had a similar indicator for those who are busy (perhaps their names can be greyed out?).  It could be  a static "availability" ie: availability at the time of the page.

The indicator on the "send page" webpage could reflect whatever the state of availability is at that moment. This would help facilitate the policy of paging everyone once (even if busy) for a heads-up, but then not paging them again for a 2nd page if they didn't respond to the first time... maybe there could even be a "unselect busy" button that unselects those who are busy.

Oh just realized that availability can be compared to event OP date. So if a member is paged on date1, and OP is date2 and member is unavailable on date3, then if date2 == date3, then we have an unavailability status for that member (current on date1)

sorry, this is like a huge functionality and a lot more complicated than a simple bug to fix, but I think it's important to reduce the cognitive workload on the DO at the time of a call-out.

**Comment by kduncklee** [comment]
Unavailable members now show in italics on message detail page. Pushed to staging. @ctaylor451 to finish front-end improvements.

**Comment by kduncklee** [comment]
Fixed by #367
