### ISSUE TITLE
Correct path for bamru.net Files

### ISSUE THREAD

**Issue by scot** [BAMRU-Tech/bamru_net#301]
Currently, the hosted path is https://bamru.net/file/
As per links in the wiki from before, it seems it should be 'files' plural. For example, see here: https://wiki.bamru.info/mediawiki/index.php/Public_Relations for linked file URLs that are '.../files/...'

**Comment by kduncklee** [comment]
I think some links were using file/, but I see the ones you're pointing to use files/. For now, both will work.

Pushed to staging. Prod push pending testing.
