### ISSUE TITLE
Event detail page: Add attendee count

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#306]
User request: add a count of attendees by status (R, FM, TM, G, etc) along with a total.

**Comment by ctaylor451** [comment]
Do you want the summary and a column with the status?  Filtered?

Or just a basis summary after each OP

**Comment by ctaylor451** [comment]
Skip the first question, I see you added an issue.  Do you want filtering?

**Comment by kduncklee** [comment]
I think a basic summary after each OP. Something like:
9 attendees (3 T, 5 FM, 1 TM)

It would be nice is empty statuses were filtered out:
8 attendees (1 T, 5 FM, 2 G)

**Comment by ctaylor451** [comment]
PR #313
