### ISSUE TITLE
Event detail page: add link to member detail page

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#307]
The link was not useful on the "add users to event" page, but is useful on the event page. This is an easy way to get to phone number, etc, especially for guests that aren't in the main roster.

**Comment by ctaylor451** [comment]
Fixed with PR #315. @kduncklee, I have mixed feels about this in that its harder to select the member for editing their leave/return times.  Maybe we should have an icon for the href
