### ISSUE TITLE
please make default team members view only TM, FM and T (exclude R and A)

### ISSUE THREAD

**Issue by cody-barkley** [BAMRU-Tech/bamru_net#318]
current team list includes Reserve and Associate.  99% of the time we just want active members (FM,TM and T).  can we make that the default?  View is in Safari.

**Comment by ctaylor451** [comment]
Would you talk to John Chang.  He requested the current paging set

**Comment by cody-barkley** [comment]
Hi, 

I don’t understand.  Current paging excludes Reserve and Associate.  My request is not for paging but for how the membership is displayed under Team -> Members and Team -> Certifications.

A possible workaround is for the default sort to be on “Status” so that R and A are at the bottom of the list.

It takes 2 seconds to change the filter or sort, so this is not a priority.

Thanks, Cody

**Comment by ctaylor451** [comment]
John wanted to page R/A on Tuesday DO change
We agreed to make the event page exclude R/A

On the Certs page seems like you might want to see R but I can easily
change the defaults

**Comment by cody-barkley** [comment]
I think easiest solution might be default is sort by “Status” and no change to default filters. Thanks.
