### ISSUE TITLE
Some guests have login access

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#338]
From talking to kduncklee it shouldn't be an issue since there's no password reset for now.

Examples: https://bamru.net/member/587 and https://bamru.net/member/583

**Comment by melinanina** [comment]
Update: looks like on new member creation we should not provide login access for guests

**Comment by ctaylor451** [comment]
Removed login access for G, MA, MN, GA, GN

**Comment by ctaylor451** [comment]
Is there a member create page? If not I'd suggest creating a new feature
request

**Comment by kduncklee** [comment]
Yes, see the member/add/ link in the team menu, for editors only.

Verified the form sets is_active = False.
