### ISSUE TITLE
No wiki access

### ISSUE THREAD

**Issue by eztzachi** [BAMRU-Tech/bamru_net#339]
Error: "Auto-creation of a local account failed: Automatic account creation is not allowed."

Tried to logout and login again but no luck.
Brooke tried from her user, same error.

**Comment by kduncklee** [comment]
Were you ever able to log in after the site transition? I just tested my account and it worked. Can you please try again to see if it was an intermittent error? I'll also check the logs.

**Comment by eztzachi** [comment]
I was able, not anymore. Issue still persist. Here's a screenshot:
![image](https://user-images.githubusercontent.com/8541806/51880730-7dbe4e80-235f-11e9-8d07-0af0c32a4acd.png)

**Comment by kduncklee** [comment]
This is pushed to production. Can you please test that it's fixed for you?

**Comment by kduncklee** [comment]
Can you please send me the page the link was on and which link is broken? I just tried one channel list and it seemed ok.

**Comment by eztzachi** [comment]
Seems like it’s fixed now. Thanks!
