### ISSUE TITLE
Participant add allows dups

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#36]
Participant add API should dedup members in an OP

**Comment by jboning** [comment]
One exciting discovery is that the database already includes some duplicates (and triplicates! see /events/2401/roster on the old system). So we can't simply apply a unique index to prevent this from happening in the future. We should consider cleaning up this table and adding a unique index as part of #37.

**Comment by jboning** [comment]
After #41, you can POST a json list of member ids to `/api/period_participants/<period_id>/` and it will ensure that all of those members are participants of that period, without adding any duplicates.

**Comment by ctaylor451** [comment]
no sure how this works - i'm still getting dups

does django unique() help with this problem?  Haven't investigated in detail

**Comment by jboning** [comment]
If you're still getting dups, that sounds like a bug. Can you describe the situation & request so I can try to repro when I get a chance?

**Comment by ninjadeathtoast** [comment]
First thing I did was try to add folks to med skills roster, OP 1. Someone had already added Melina, so I tried to add her again to test. She's on there twice now. I won't touch for a few days if you want to look at it.

**Comment by kduncklee** [comment]
Fixed in PR #90
