### ISSUE TITLE
DO shifts data

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#383]
Thanks for implementing the data point on the number of shifts people have done in the past year. Just wanted to check whether the data is correct.

When I'm planning for Q2, the shifts in the past year shows 0 for me (I had a shift in Q3) and 2 for Jacobs (he had one in Q3 and one in Q4). Is it just a rolling 365 days?

**Comment by ctaylor451** [comment]
Melina, I checked the code, looks good to me.  It is computed based on quarters.
You had one shift Q1/2018 so for Q1/2019 planning it shows 1 and for Q2/2019 it shows 0 (which is correct for previous 4 quarters Q2/18, Q3/18, Q4/18, Q1/19).  For any planning period it is the previous 4 quarters
