### ISSUE TITLE
Bamru.net timestamp off by one hour

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#387]
Blake Gleason via gmail.com 
Fri, Mar 1, 12:42 PM
to me

Is off by an hour

Eg, Tzachi sent page at 10am but it's shown as 9am.

Craig Taylor <ctaylor@2ct.com>
Tue, Mar 19, 10:22 AM (7 days ago)
to Blake

Do you have any more detail?  I did a test page and things look OK

Blake Gleason via gmail.com 
Wed, Mar 20, 2:26 PM (6 days ago)
to me

Looks like March 10 DST transition may have "fixed" the problem.

I just looked at several Tuesday morning DO change pages from prior to March 10.  All the ones I looked at are logged as 0700-ish on the message log, but I suspect they were all sent at (or within a minute or two of) 0800.

**Comment by jboning** [comment]
We've been displaying the month where the minute should go, so a page sent at 0756 in March would appear to have been sent at 0703.
