### ISSUE TITLE
Consider adding a new role Mob/Demob on event OP

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#400]

**Comment by kduncklee** [comment]
This could have been useful for logistics/vehicle support on the recent operation. Maybe make it more generic and call it "logistics"?

Maybe it would be simpler if it were exposed as a drop-down to select AHC/OL/Logistics in the edit dialog? I don't see a case where we would want more than one in a given OP.

**Comment by ctaylor451** [comment]
Logistics makes sense. If you can add the backend support, I'll be back mid
September and can update the UI.

**Comment by kduncklee** [comment]
Added logistics in 0c531bf. It's currently a boolean like OL and AHC. Leaving issue open for dropdown UI.

**Comment by kduncklee** [comment]
This is fine for now, closing.
