### ISSUE TITLE
phone number link  (tel attr) does not work properly on iphone

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#402]
phone number link in members section does not work properly in IOS 12 / Safari. When pressed, this message shows.

tested by Erik  Peterson, error reproduced by Cody Barkley. 
 
![276](https://user-images.githubusercontent.com/1657391/56064416-cd89a080-5d26-11e9-9ad6-f72af6f4bf65.png)

**Comment by ekhco** [comment]
This might  be environment specific, I have Android and clicking on phone number takes me to my calling app no problem.

**Comment by jboning** [comment]
I tried with an iOS device, I now see "+1 <ahref"

**Comment by kduncklee** [comment]
Confirmed fixed by #405
