### ISSUE TITLE
Auto notification of expired certs

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#406]
The old website provide auto notification sent as email when certs were going to expire
3 months, 1 month, 1 week seem like reasonable notification intervals.  Message to the individual and OO?

**Comment by ctaylor451** [comment]
Can we close this issue?

**Comment by kduncklee** [comment]
Not enabled yet. I want to test the celery scheduler a bit more before turning it on.

**Comment by kduncklee** [comment]
Notifications are enabled on prod. Closing.
