### ISSUE TITLE
"Add me" link on Event OPs

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#420]
It's very common to add yourself to an event. Please add a button to add oneself to an OP.

**Comment by ctaylor451** [comment]
Would you, @kduncklee, be OK with it on the submenu (two 'clicks' away)?  Trying to minimize the UI elements

**Comment by kduncklee** [comment]
Yes, that's fine. Another option would be to make "Add" a menu with "me" and "others" in the dropdown.
