### ISSUE TITLE
Add ability to convert meeting hours to sign-in/sign-out times

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#434]
Most meetings have everyone there for a fixed period. Add the ability to convert meeting hours to sign-in/sign-out times. This will let us account for hours.

**Comment by ctaylor451** [comment]
Do you really want this to be automatic?  Is it easy to undo if there is an exception?  I've added UI that lets you set the times but it is an extra step

**Comment by kduncklee** [comment]
Yes, it's just for meetings. I can't think of any cases where you would not want this behavior. It only updates if there are no transit or sign-in times.

If there is an exception, you can override with the times you want and it won't touch them.
