### ISSUE TITLE
Add OL needed page option

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#437]
Page to just the OLs

**Comment by ctaylor451** [comment]
Is the current method lacking?
event->page->Are you available->clear all->search "OL", select all.

or if you want all OL regardless of whether they have already responded

event->page->Broadcast->clear all->search "OL", select all.

**Comment by kduncklee** [comment]
This came up in the DO training.

That's a clever way to do it, but might be a bit involved during the heat of a callout. You also need to do "more -> search ->" in the flows above. It will also not work if someone joins with "ol" in their name.

**Comment by ctaylor451** [comment]
Talked to Cody @cody-barkley  (OO) and he is OK with search to find OLs.  Hopefully this will get documented on the wiki
