### ISSUE TITLE
Member DO availabilty errs on dev machine

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#469]
patch fails with:
{"non_field_errors":["The fields year, quarter, week, member must make a unique set."]}

but the data looks unique, let's talk when you have a minute @kduncklee 

Appears to be a timing issue but I don't understand the cause

**Comment by kduncklee** [comment]
I can't reproduce. Can you please send me your dev database?

**Comment by ctaylor451** [comment]
Let's talk, I don't think it's data related. If I check the boxes one at a
time it works.

Mainly I'd like your thoughts on the best way to debug this

**Comment by ctaylor451** [comment]
From the BROWSER (short version, full dump below):
{"available":true,"assigned":false,"comment":"","start":"2019-09-24T08:00:00","end":"2019-10-01T07:59:00","id":11079,"year":2019,"quarter":4,"week":1,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-10-01T08:00:00","end":"2019-10-08T07:59:00","id":11080,"year":2019,"quarter":4,"week":2,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-10-08T08:00:00","end":"2019-10-15T07:59:00","id":11081,"year":2019,"quarter":4,"week":3,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-10-15T08:00:00","end":"2019-10-22T07:59:00","id":11082,"year":2019,"quarter":4,"week":4,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-10-22T08:00:00","end":"2019-10-29T07:59:00","id":11083,"year":2019,"quarter":4,"week":5,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-10-29T08:00:00","end":"2019-11-05T07:59:00","id":11084,"year":2019,"quarter":4,"week":6,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-11-05T08:00:00","end":"2019-11-12T07:59:00","id":11085,"year":2019,"quarter":4,"week":7,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-11-12T08:00:00","end":"2019-11-19T07:59:00","id":11086,"year":2019,"quarter":4,"week":8,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-11-19T08:00:00","end":"2019-11-26T07:59:00","id":11087,"year":2019,"quarter":4,"week":9,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-11-26T08:00:00","end":"2019-12-03T07:59:00","id":11088,"year":2019,"quarter":4,"week":10,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-12-03T08:00:00","end":"2019-12-10T07:59:00","id":11089,"year":2019,"quarter":4,"week":11,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-12-10T08:00:00","end":"2019-12-17T07:59:00","id":11090,"year":2019,"quarter":4,"week":12,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-12-17T08:00:00","end":"2019-12-24T07:59:00","id":11091,"year":2019,"quarter":4,"week":13,"member":367}
{"available":true,"assigned":false,"comment":"","start":"2019-12-24T08:00:00","end":"2019-12-31T07:59:00","id":11092,"year":2019,"quarter":4,"week":14,"member":367}

From the SERVER:
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-10-01T08:00:00', 'end': '2019-10-08T07:59:00', 'id': 11080, 'year':
2019, 'quarter': 4, 'week': 2, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-10-22T08:00:00', 'end': '2019-10-29T07:59:00', 'id': 11083, 'year':
2019, 'quarter': 4, 'week': 5, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-10-15T08:00:00', 'end': '2019-10-22T07:59:00', 'id': 11082, 'year':
2019, 'quarter': 4, 'week': 4, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-10-08T08:00:00', 'end': '2019-10-15T07:59:00', 'id': 11081, 'year':
2019, 'quarter': 4, 'week': 3, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-10-29T08:00:00', 'end': '2019-11-05T07:59:00', 'id': 11084, 'year':
2019, 'quarter': 4, 'week': 6, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-09-24T08:00:00', 'end': '2019-10-01T07:59:00', 'id': 11079, 'year':
2019, 'quarter': 4, 'week': 1, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11082/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11080/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11081/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11084/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11083/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11079/ HTTP/1.1" 200 163
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-11-05T08:00:00', 'end': '2019-11-12T07:59:00', 'id': 11085, 'year':
2019, 'quarter': 4, 'week': 7, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-11-12T08:00:00', 'end': '2019-11-19T07:59:00', 'id': 11086, 'year':
2019, 'quarter': 4, 'week': 8, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11085/ HTTP/1.1" 200 163
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-12-03T08:00:00', 'end': '2019-12-10T07:59:00', 'id': 11089, 'year':
2019, 'quarter': 4, 'week': 11, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-11-19T08:00:00', 'end': '2019-11-26T07:59:00', 'id': 11087, 'year':
2019, 'quarter': 4, 'week': 9, 'member': 367}
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-12-10T08:00:00', 'end': '2019-12-17T07:59:00', 'id': 11090, 'year':
2019, 'quarter': 4, 'week': 12, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11086/ HTTP/1.1" 400 87
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-11-26T08:00:00', 'end': '2019-12-03T07:59:00', 'id': 11088, 'year':
2019, 'quarter': 4, 'week': 10, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11089/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11087/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11090/ HTTP/1.1" 400 87
[18/Nov/2019 17:16:10] "PATCH /api/do/11088/ HTTP/1.1" 200 164
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-12-17T08:00:00', 'end': '2019-12-24T07:59:00', 'id': 11091, 'year':
2019, 'quarter': 4, 'week': 13, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11091/ HTTP/1.1" 200 164
{'available': True, 'assigned': False, 'comment': '', 'start':
'2019-12-24T08:00:00', 'end': '2019-12-31T07:59:00', 'id': 11092, 'year':
2019, 'quarter': 4, 'week': 14, 'member': 367}
[18/Nov/2019 17:16:10] "PATCH /api/do/11092/ HTTP/1.1" 200 164

From the BROWSER (full dump):
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-09-24T08:00:00","end":"2019-10-01T07:59:00","id":11079,"year":2019,"quarter":4,"week":1,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-10-01T08:00:00","end":"2019-10-08T07:59:00","id":11080,"year":2019,"quarter":4,"week":2,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-10-08T08:00:00","end":"2019-10-15T07:59:00","id":11081,"year":2019,"quarter":4,"week":3,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-10-15T08:00:00","end":"2019-10-22T07:59:00","id":11082,"year":2019,"quarter":4,"week":4,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-10-22T08:00:00","end":"2019-10-29T07:59:00","id":11083,"year":2019,"quarter":4,"week":5,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-10-29T08:00:00","end":"2019-11-05T07:59:00","id":11084,"year":2019,"quarter":4,"week":6,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-11-05T08:00:00","end":"2019-11-12T07:59:00","id":11085,"year":2019,"quarter":4,"week":7,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-11-12T08:00:00","end":"2019-11-19T07:59:00","id":11086,"year":2019,"quarter":4,"week":8,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-11-19T08:00:00","end":"2019-11-26T07:59:00","id":11087,"year":2019,"quarter":4,"week":9,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-11-26T08:00:00","end":"2019-12-03T07:59:00","id":11088,"year":2019,"quarter":4,"week":10,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-12-03T08:00:00","end":"2019-12-10T07:59:00","id":11089,"year":2019,"quarter":4,"week":11,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-12-10T08:00:00","end":"2019-12-17T07:59:00","id":11090,"year":2019,"quarter":4,"week":12,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-12-17T08:00:00","end":"2019-12-24T07:59:00","id":11091,"year":2019,"quarter":4,"week":13,"member":367}
browser.sentry-cdn-5.5.0-bundle.min.js:2
{"available":true,"assigned":false,"comment":"","start":"2019-12-24T08:00:00","end":"2019-12-31T07:59:00","id":11092,"year":2019,"quarter":4,"week":14,"member":367}
VM279:1 PATCH http://13.66.153.216:8000/api/do/11081/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11080/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11082/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11084/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11083/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11086/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11089/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11087/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2
VM279:1 PATCH http://13.66.153.216:8000/api/do/11090/ 400 (Bad Request)
(anonymous) @ VM279:1
(anonymous) @ browser.sentry-cdn-5.5.0-bundle.min.js:2
send @ datatables.min.js:14
ajax @ datatables.min.js:14
UpdateRow @ 367:487
(anonymous) @ 367:405
(anonymous) @ datatables.min.js:185
iterator @ datatables.min.js:145
(anonymous) @ datatables.min.js:185
(anonymous) @ datatables.min.js:147
SetAll @ 367:401
k @ datatables.min.js:240
(anonymous) @ datatables.min.js:241
dispatch @ datatables.min.js:14
y.handle @ datatables.min.js:14
sentryWrapped @ browser.sentry-cdn-5.5.0-bundle.min.js:2

**Comment by kduncklee** [comment]
This is caused by https://github.com/encode/django-rest-framework/issues/5760. It's much more likely on the dev machine due to the slower python debug server.

The fix is scheduled for the next DRF release, but it's been delayed a bunch.
