### ISSUE TITLE
'More events' table on event_list should show the next year's events by default

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#473]
Currently the 'More events' table only shows events from the current year. It would be helpful to show next year's events without having to change the date filter.

**Comment by ctaylor451** [comment]
What behavior are you expecting?  "More events" shows all events for the current year

**Comment by kduncklee** [comment]
It's November of 2019. I'd like to see 2020.

Maybe show all of the current and next year?

**Comment by ctaylor451** [comment]
I could also do +/- 6 months or 1 year plus first 3 months.  2 years is
easy just more mobile data on the initial load

**Comment by kduncklee** [comment]
The next years events are only created in November when the TO is done with the calendar. I don't see this as too much additional data. I don't think we should remove anything from the current year, as people may need to look back over the year for reporting.
