### ISSUE TITLE
Improve performance of Messages page

### ISSUE THREAD

**Issue by genev** [BAMRU-Tech/bamru_net#475]
We have a lot of messages and we show all of them when a user navigates to https://bamru.net/message/

We should not load all of them since it takes a few seconds. Pagination would be great here.

**Comment by kduncklee** [comment]
@ctaylor451: Would you prefer to convert this to an API call and use DRF pagination or I can add Django pagination on the back end?
https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination
