### ISSUE TITLE
Outgoing DO is not being cleared on transition

### ISSUE THREAD

**Issue by ajnisbet** [BAMRU-Tech/bamru_net#488]
All the DOs since 8c4e1c13d0 have `member.is_current_do == True`. This lists them on `/do_ahc_status`, and gives them the CURRENT DO banner on their member page.

Probably what's needed is  something like `current_scheduled_do.set_do(False)` in https://github.com/BAMRU-Tech/bamru_net/blob/8b31541f2abe6db9bf80e58ed2ef0e5d4342fe27/main/serializers.py#L235-L236 but I don't know enough to make the change (e.g., why the difference between `is_current_do` and `current_scheduled_do`).

**Comment by ctaylor451** [comment]
Can you see the remove button?

**Comment by ajnisbet** [comment]
Ah I see that now, could add a step to the DO transition guide to tidy up the list.

**Comment by ctaylor451** [comment]
We need a more formal DO hand-off procedure. For now we could add it to the
DO instructions

**Comment by ctaylor451** [comment]
For now I've removed the previous DOs

**Comment by kduncklee** [comment]
The idea is to make it a manual step in case there is a call in progress during the transition. We don't want the old DO to get kicked off the mailing list. We'll add it to the checklists once the whole flow is in place.

**Comment by kduncklee** [comment]
The DO list integration is now working. Assigning to Cody to update the DO documentation.

**Comment by kduncklee** [comment]
Wiki is updated. Closing.
