### ISSUE TITLE
Member Profile view does not show multiple versions of the same certificate type

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#515]
For example, if a member has multiple ICS certs, only one is shown on the list. The full list is show on the edit certs page.

**Comment by ctaylor451** [comment]
Can you send me an example, does this apply to you?  I'll try to fix it
before I leave

**Comment by ctaylor451** [comment]
I see it now, will look into it

**Comment by ctaylor451** [comment]
fix and pushed to staging, move to prod at your leisure

**Comment by kduncklee** [comment]
Thanks for the speedy fix!
