### ISSUE TITLE
images from bamru.net not loading on wiki

### ISSUE THREAD

**Issue by cody-barkley** [BAMRU-Tech/bamru_net#521]
Hi, it looks like images from bamru.net are not loading the wiki.  Can someone please investigate ?

TTRS wiki page:
https://wiki.bamru.info/mediawiki/index.php/Technical_Systems/TTRS

SMC Alert page:
https://wiki.bamru.info/mediawiki/index.php/SMC_Alert_Paging

**Comment by kduncklee** [comment]
This looks to have been caused by a browser update. It still worked on an old version of Safari. Migrating the wiki from bamru.info to bamru.net fixed the same-origin issue.

Image loading is fixed.
