### ISSUE TITLE
Column visibility on members page broken on Firefox

### ISSUE THREAD

**Issue by genev** [BAMRU-Tech/bamru_net#522]
**To reproduce:**

1. Go to https://bamru.net/member/
2. Click More
3. Click Column visibility

Chrome Version 85.0.4183.83 works
Firefox Version 80.0.1 does not work

Both are running on MacOS Mojave 10.14.6

**Comment by kduncklee** [comment]
Column visibility now doesn't show up for me on Chrome 86.0.4240.80 on OS X.

I tried updating to https://cdn.datatables.net/v/ju-1.12.1/jq-3.3.1/jszip-2.5.0/dt-1.10.22/b-1.6.5/b-colvis-1.6.5/b-html5-1.6.5/b-print-1.6.5/cr-1.5.2/r-2.2.6/sl-1.3.1/datatables.js, but it still didn't work.
