### ISSUE TITLE
Member list does not display correctly on Firefox

### ISSUE THREAD

**Issue by ninjadeathtoast** [BAMRU-Tech/bamru_net#536]
bamru.net/member only displays name, phone, and email columns on Firefox. Green plus shows Status/roles, but on chrome those show up as their own columns (which personally I prefer). I tried adjusting window size. Clicking on "More" > "Column Visibility" didn't do anything in either browser.

Very low priority.

**Comment by ctaylor451** [comment]
Try increasing the size of your window.  Clicking ColVis won't help unless you remove some other columns.
