### ISSUE TITLE
Add more flexible Cert handling

### ISSUE THREAD

**Issue by kduncklee** [BAMRU-Tech/bamru_net#555]
Here is a proposal to make the Cert model more flexible and enable new cert types and combinational certs. Please respond with suggestions and comments.

### CertType
This new model represents one of the headers on the team cert page.
- name (medical, cpr, ham, SO, ...)
- showAll - combine all in view (ICS: 100,200 instead of 200*)
- hasSubtype - use SubType name instead of description
- helpText - Show this text on the add/edit form
- template - Optional jinga2 template to show as display text instead of top Cert. This is used to combine subcerts like SO driver practical and SO driver classroom into a single SO cert. It will also be used to display promotions/endorsements (#190).

The following enable Cert fields in the add/edit form:
- hasExpiration
- hasEarnedDate
- hasDescription
- hasLink
- hasFile

### CertSubtype
Shows one of the options for Cert
- type (CertType foreign key)
- name - display text (WFR, EMT, FA)
- position - ordering if there are multiple
- isOther - show Cert description instead of CertSubtype name (max 1 of these per type). If no isOther is listed, all certs must be one of the listed subtypes.

### Cert
Existing model. Main change is to add foreign keys:
- type
- subtype

**Comment by tyeh26** [comment]
Done
