### ISSUE TITLE
Consider moving message app back into main app

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#57]
The separation doesn't seem to buy us much and the directories structures are harder to search

message/view.py vs
main.view/member_views.py

at a minimum we should create message_views.py

**Comment by jboning** [comment]
I'm +1 to this. There's a directory division, but no real layer of abstraction, in the sense that the message app directly uses models from the main app. We might be able to come up with some other interface that decouples the message sending more cleanly.

**Comment by ctaylor451** [comment]
I've moved the views and templates to main.  I left the rest of the code for @kduncklee

**Comment by ctaylor451** [comment]
@kduncklee Any reason do to?
