### ISSUE TITLE
Ranks and Roles are commingled 

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#59]
At some point we need to separate roles from ranks
ranks = TM, FM, T, G, Associate, Support
roles = R, Alum, no-contact, active

will require db and ui changes

**Comment by ninjadeathtoast** [comment]
Roles also seem to be pulling historical data. Kantarjiev is listed as Training officer, and Ethan is listed as XO, for example

**Comment by ctaylor451** [comment]
I can update the data but this is a test database and all changes will be deleted eventually.  The old website database is the source of truth.  btw, who is this, ninjadeathtoast.  I would be nice to have a little info in your profile

**Comment by ctaylor451** [comment]
Looking at the old database, in looks out of date as well.  I don't see Adam as XO

**Comment by ninjadeathtoast** [comment]
Sorry! It's Adam. I'll fix profile when I have a moment on my computer

**Comment by ctaylor451** [comment]
After last night's discussion I add TM, FM, T, R, A,S to the default selection.  We can debate R.
We either need to use the Guest Alum category for old guests or an inactive flag for old guests

I'd also like to add a attribute with someone's highest promotion

**Comment by ctaylor451** [comment]
Closing this issue and effectively replacing it with #190.  Rank goes away and is replaced with membership category.  Promotions are recorded as certs
