### ISSUE TITLE
Clarify whether an event is published to the BAMRU public calendar

### ISSUE THREAD

**Issue by scot** [BAMRU-Tech/bamru_net#628]
Issue: it is unclear whether an Event is published to the bamru.net public calendar. 

Current wording: "Published:"
Suggestion: "Visible on the BAMRU public calendar:" or "Publish publicly:"

File: main/templates/event_detail.html
L91

**Comment by kduncklee** [comment]
The event edit page currently has the help text "Published events are viewable by the public." Do you think we should change that as well?

**Comment by tyeh26** [comment]
Done in [651](https://github.com/BAMRU-Tech/bamru_net/issues/651)

**Comment by tyeh26** [comment]
Done in [651](https://github.com/BAMRU-Tech/bamru_net/issues/651)
