### ISSUE TITLE
Inaccurate participant count on Reports/Activity Summary page

### ISSUE THREAD

**Issue by simonffox** [BAMRU-Tech/bamru_net#629]
On the Member Activity reports page, the "Unit-wide Summary" "Participants" section seems to overcount participants. It seems to count each person attending each event as unique (If ABC has attended 6 operations, so they get counted as 6 people who have attended an operation -- essentially it's doing a sum() over the column instead of a count()).

I have suggested a simple code summing fix below, which may or may not work. I was not able to test this change.

File & Location: https://github.com/BAMRU-Tech/bamru_net/blob/5cee6f934540ad988ce461d8c627a75d78fd2185/main/views/report_views.py#L117
```
# before
        unit_totals = [0, 0]
        for member in members:
            member.total_events = 0
            member.total_hours = 0
            member.type_totals = member_type_totals[member.id]
            for k, v in member.type_totals.items():
                member.total_events += v[0]
                member.total_hours += v[1]
                unit_totals[0] += v[0]
                unit_totals[1] += v[1]
                type_totals[k][0] += v[0]
                type_totals[k][1] += v[1]

# after
        unit_totals = [0, 0]
        for member in members:
            member.total_events = 0
            member.total_hours = 0
            member.type_totals = member_type_totals[member.id]
            for k, v in member.type_totals.items():
                member.total_events += v[0]
                member.total_hours += v[1]
                if unit_total[0] == 0:
                    unit_totals[0] += v[0]
                unit_totals[1] += v[1]
                type_totals[k][0] += v[0]
                type_totals[k][1] += v[1]
```

**Comment by tyeh26** [comment]
fyi, `unit_total[0] == 0` will only be true once since it's defined outside of the `for member in members` loop. I ended up checking in the `for member` loop after the loop that processes the member's events.  Check if the member's events are non-zero and increment the # of unit participants by 1 (instead of v[0]), if so.
