### ISSUE TITLE
member_do_list should use std table display

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#68]

**Comment by ctaylor451** [comment]
WIP

**Comment by ctaylor451** [comment]
Fixed #230

**Comment by ctaylor451** [comment]
This needs more work.  The do list API only returns filled in entries.  The do create API doesn't seem to take a member id (am I missing something @kduncklee ).  Given the "business logic" aspects of this (calc # of weeks in a qtr) should the do list API return a complete set of week objects for the qtr by creating empty objects or should we implement this in JS?  Do one of you @jboning or @kduncklee have time to look at this?

**Comment by jboning** [comment]
My kneejerk reaction is that since we already have the weeks-in-quarter
logic, we shouldn't duplicate it in Python. Not sure when I'll have a
chance to look--maybe tomorrow
