### ISSUE TITLE
is_active should mean something

### ISSUE THREAD

**Issue by ctaylor451** [BAMRU-Tech/bamru_net#70]
As far as I can tell all members are active

**Comment by kduncklee** [comment]
The is_active member field is used by the Django backend to decide who can log in.

**Comment by ctaylor451** [comment]
Maybe we should rename this to is_allowed_login or some such.  Active is a heavily overloaded word

**Comment by kduncklee** [comment]
This comes from Django:
https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.is_active

**Comment by ctaylor451** [comment]
There seems to be some confusing between the auth model and active BAMRU members.
Currently R is not is_active in the django filter context

**Comment by ctaylor451** [comment]
I've removed the IsActive django filters in all the templates and replaced it with view filters
