### ISSUE TITLE
UI: consider putting menu items directly on splash page

### ISSUE THREAD

**Issue by ekhco** [BAMRU-Tech/bamru_net#79]
On mobile phone layout, when you first land on bamru.info, the user has to click on the "3 bar" icon in the top corner to expand out the options to select "Events, Team, Library etc."

Consider putting permanent buttons on the splash page (the space that reads "Welcome to BAMRU.net. Please use ...") so that a mobile phone user does not have to waste a click on opening the menu.

**Comment by ctaylor451** [comment]
Agreed, we could do that or just make the event page be the index page.  We just stuck up an index page as a placeholder
