### ISSUE TITLE
Better logic for edit permissions

### ISSUE THREAD

**Issue by jboning** [BAMRU-Tech/bamru_net#8]
In a couple of places (see below), there's a check that the current user can only edit their own info. We probably want something smarter than this. The secretary, at least, should be able to edit anyone.

https://github.com/BAMRU-Tech/bamru_net/blob/844fb98feb31fd365827da6468f2108d13fa4a1b/main/views/member_views.py#L111
https://github.com/BAMRU-Tech/bamru_net/blob/844fb98feb31fd365827da6468f2108d13fa4a1b/main/views/member_views.py#L154

**Comment by andyl** [comment]
When we come back to this: craig and I designed a flexible permissioning scheme & would like to see this find it's way into the system someday.

**Comment by jboning** [comment]
Is that design written down somewhere? It might be more work than we want to do for v1, but I'd like to look at it--if it's simple, then we can avoid writing a temporary hack.

**Comment by ctaylor451** [comment]
Not simple enough for MVP.  The admin interface is the is the ultimate hammer.  This feels like release 1.5 or later to me
