### ISSUE TITLE
Add event participants: what does expand detail do?

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#80]
I clicked on it and it didn't change anything in the UI.

![image](https://user-images.githubusercontent.com/19847087/46907424-086d6180-cec7-11e8-98a7-576796b01d1b.png)

**Comment by melinanina** [comment]
Seems to work on mobile only

**Comment by code-jockey** [comment]
On the desktop, if you shrink the browser width so that some of the table columns are not visible, then it will display the information of the hidden columns.

**Comment by melinanina** [comment]
Ah, yes, I tested that now and it makes sense.

**Comment by melinanina** [comment]
I think removing it would be best.

**Comment by ctaylor451** [comment]
Fixed in PR#113
