### ISSUE TITLE
Improved UX for creating/viewing event

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#82]
- [x] Add a link to Google Maps from the event page (as in current bamru.net). Might be able to pull in Google Map APIs to get correct addresses and locations (if that's easy).

- [x] For event leaders, pull information from the roster so that one can click from the event and get taken to their contact information page.

Not sure what this shows:
![image](https://user-images.githubusercontent.com/19847087/46907538-d6f59580-cec8-11e8-80cb-73eeacab5f39.png)

**Comment by ctaylor451** [comment]
I added the Geo picking (works locally) but it using http: and we use https: for production server (@kduncklee is there some way to relax this?)

Also it looks like the geo picker is going away because of how Google charges for map data.

**Comment by ctaylor451** [comment]
Partial fix #389
