### ISSUE TITLE
Confusing navigation on events page

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#83]
The navigation through the event pages is a bit confusing. The navigation bar takes me to upcoming events
![image](https://user-images.githubusercontent.com/19847087/46907563-479cb200-cec9-11e8-9268-3fd129569ac6.png)

Clicking on Events from the events navigation bar on a specific event takes me back all events. I would expect it to take me to upcoming events.
![image](https://user-images.githubusercontent.com/19847087/46907566-5b481880-cec9-11e8-9572-5d149712b3da.png)

If you want to keep that flow, I'd recommend updating the navigation bar to "Upcoming events" to make that more clear.

**Comment by ctaylor451** [comment]
Changed navbar to upcoming events but this still need thought

**Comment by ctaylor451** [comment]
Rewrote event page to show Upcoming, Recent and All (w/date selection) events
