### ISSUE TITLE
DO scheduling issues and features

### ISSUE THREAD

**Issue by melinanina** [BAMRU-Tech/bamru_net#85]
- [x] if possible, note the number of DO shifts a particular person has had the previous 4 quarters. I'm trying to be equitable and am currently tracking this information in a spreadsheet.
- [x] Remove the X in the cell when a DO is scheduled. It's a bit confusing and not necessary.
![image](https://user-images.githubusercontent.com/19847087/46907650-939c2680-ceca-11e8-9e4e-d023ef94deaa.png)

- [x] availability link from the DO scheduling is broken
![image](https://user-images.githubusercontent.com/19847087/46907660-baf2f380-ceca-11e8-9ea2-c297a32c3cf1.png)
- [ ] make the "plan" button only available to admin users please :)

**Comment by kduncklee** [comment]
Items 1 and 3 are fixed in PRs #89 and #91.

**Comment by ctaylor451** [comment]
Who should be allowed to access the planning page?  Do we have a defined role? @kduncklee

**Comment by kduncklee** [comment]
Split the permissions issue into #362.
