### ISSUE TITLE
Dropdowns for category menus not working on iOS devices

### ISSUE THREAD

**Issue by code-jockey** [BAMRU-Tech/bamru_net#93]
The Team, Library, Action, etc. drop-down are not working on iOS devices. I tried 2 iPhones and an iPad using 5 different browsers and all had the same issue. Nothing happens.

**Comment by ctaylor451** [comment]
Upgraded to bootstrap 4.1.1, let me know if it helped

**Comment by ctaylor451** [comment]
Needs verification

**Comment by willgilmore** [comment]
This works for me.
I just tied with a iPhone 6p on iOS 12.1

**Comment by ctaylor451** [comment]
Tested by John

**Comment by ctaylor451** [comment]
Thanks

**Comment by willgilmore** [comment]
No problem. :)
